apiVersion: v1
kind: ConfigMap
metadata:
  name: forge-runtime-projects
  namespace: forge-system
data:
  runtime-projects.json: |
    {
      "projects": [
        {
          "projectId": "adesco-webb",
          "repository": "https://github.com/mkjellma/adesco.git",
          "allowedBranch": "main",
          "buildProfile": "nextjs-npm",
          "runtimeProfile": "private-http",
          "registryRepository": "forge/adesco-webb"
        }
      ]
    }
