apiVersion: v1
kind: Namespace
metadata:
  name: forge-runtime
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forge-runtime-executor
  namespace: forge-runtime
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forge-runtime-executor
  namespace: forge-runtime
subjects:
  - kind: ServiceAccount
    name: forge-build-executor
    namespace: forge-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forge-runtime-executor
